INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (1, 1, 'BEGINNER', 11, 'What is big int ? ', 1);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (2, 3, 'BEGINNER', 11, 'What is big love ? ', 1);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (3, 1, 'BEGINNER', 11, 'What is TCP? ', 6);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (4, 1, 'ADVANCED', 11, 'What is UDP? ', 7);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (6, 1, 'ADVANCED', 14, 'A radio box question that works ? *WOOOOOOOOOOOW*', 1);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (7, 1, 'BEGINNER', 14, 'PostgreSQL', 1);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (9, 2, 'BEGINNER', 7, 'PostgreQuestion', 1);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (5, 2, 'INTERMEDIATE', 69, 'Why BIBLETHUMP?  z', 2);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (19, 2, 'INTERMEDIATE', 15, 'A question with 2 initial answers.', 10);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (20, 2, 'INTERMEDIATE', 7, '    Kill me', 9);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (21, 1, 'ADVANCED', 2, '    qqqqqqqqqqqqqqqq', 9);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (22, 1, 'INTERMEDIATE', 33, '    wwwwwwwwwwwwwwwwwwwwww', 10);
INSERT INTO public.questions (id, correct_answer_count, level, points, question, topic_entity_id) VALUES (23, 2, 'BEGINNER', 4, '    sssssssssssssssssssssssssssssss', 6);